language: node_js
node_js:
  - "0.12"
  - "0.11"
  - "0.10"
  - "4.2.2"
  - "5.1.0"
  - "iojs"
after_success:
  - ./node_modules/.bin/mocha -R mocha-lcov-reporter | ./node_modules/coveralls/bin/coveralls.js
