language: node_js
node_js:
  - "4"
  - "5"
  - "node"
after_success:
  - ./node_modules/istanbul/lib/cli.js cover ./node_modules/mocha/bin/_mocha tests/**/*.js
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
